services:
  - type: web
    name: weather-dashboard
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: DATABASE_URL
        value: postgres://airflow:airflow@postgres:5432/airflow
